### ISSUE TITLE
Get a List of Meals

### ISSUE THREAD

**Issue by omorgenroth** [omorgenroth/capstone-project#1]
As a **User**, 
 I need **to see a List of Meals**, 
 so that **to get an Overview of what Meals are availabe**. 

### Description 
![Home_Wireframe](https://user-images.githubusercontent.com/71653845/99973645-458fc780-2da0-11eb-9efc-8a161cc278f2.png)
![Choose-Meal_Wireframe](https://user-images.githubusercontent.com/71653845/99973654-488ab800-2da0-11eb-9d00-33b2cfe98df1.png)

### Acceptance Criteria

- User can click on "Create" and get an Overview of all available Meals ( as Overlay)
- User can click the "X" in the upper left Corner to get back ( to the Homescreen)
- Data comes from own API-Endpoint 

### Tasks 
- [x] Setup a Project with /Frontend and /Backend
- [x] Create React App in /Frontend and delete .git Folder
- [x] Create a new Symfony Project in /Backend and delete .git Folder
- [x] Setup Dish/Ingredient Entity  and migrate DB
- [x] Setup API Endpoint for DishEntity 
- [x] Fill Database with Test Data 
- [x] Create Component for Dish-Item
- [x] Fetch Data from API and display it in React App
- [x] Create Basic Styling (just mobile)
- [x] Write Basic Tests

### Complexity 
 - medium
