### ISSUE TITLE
User can add Ingredients

### ISSUE THREAD

**Issue by omorgenroth** [omorgenroth/capstone-project#14]
As a **User**, 
 I need to **add additional Ingredients**
to **customize** my Shoppinglist, 

### Acceptance Criteria
- User can add existing Ingredients to the Shoppinglist by searching for them

### Tasks 
- [ ] Set up API for GET/ingredients 
- [ ] Set up API for Get/category/id
- [ ] Setup Form Component to add ingredient
- [ ] Add Search Logic 

### Complexity 
- small
