### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by omorgenroth** [omorgenroth/capstone-project#16]
As a **User**, 
 I need to **be able to login with my personal User Account**
to **store and retrieve my personal Lists**

### Acceptance Criteria
- User can Login on Frontend and will recieve his active List from Backend
- The Password will be encoded on Backend before storing it in the DB
- After successful Login the Client will receive a Token from Server to authenticate the API-Calls

### Tasks 
- [x] Set up API for /login and /register
- [x] Add Token Entity and relate to User Entity
- [x] Setup Password Encoding
- [x] Setup Login Page and Login Components
- [x] Setup Global State for User 

### Complexity 
- large
