### ISSUE TITLE
Create a Meal Plan

### ISSUE THREAD

**Issue by omorgenroth** [omorgenroth/capstone-project#2]
As a **User**, 
 I need to be able to **select Meals from the Meal Overview**
so that i can **create my own Meal Plan**

### Description 
![Choose-Meal-selected_Wireframe](https://user-images.githubusercontent.com/71653845/99911219-2555ff00-2cf3-11eb-8dea-32b8450677f2.png)
![Overview-selected-Meals_Wireframe](https://user-images.githubusercontent.com/71653845/99911224-28e98600-2cf3-11eb-80ee-fe4f30d230f3.png)

### Acceptance Criteria

- The user can mark one or more Meals as selected by clicking/touching them
- A second click/touch from user would delesect the Meal
- A selected Meal must be easy to distinguish from the deselected 
- A Counter shows the amount of Meals selected
- A button for creating the List is active as soon as at least one Meal is selected (default: disabled)
- The Button is always visible while scrolling trough the List
- By clicking the Button, the user get`s redirected to a ReviewPage with the selected Items
- On the Review Page the User can delete single Items from the List

### Tasks 
- [x] Add ToggleLogic to Items
- [x] Add Styling to selected Items
- [x] Add CountLogic and fixed Button
- [x] Add Review Page
- [x] Add Tests

### Complexity 
- small
