### ISSUE TITLE
Filter Dishes by Name

### ISSUE THREAD

**Issue by omorgenroth** [omorgenroth/capstone-project#9]
As a **User**, 
 I need **to filter the Dishes in the Overview Page**, 
 so that ** i can find wanted Dishes without scrolling the whole List**. 

### Description 
(Text, Scribble, Wireframe, Design)

### Acceptance Criteria
- By clicking the filter icon in the OverlayHeader the User get´s an Input Field
- Over that Input Field the User can filter the current Overview by Name
- Over the ResetButton the User can reset the Filter Input
- The User needs to have a Button to quickly leave the Filter Mode

### Tasks 
- [ ] Add Filter Logic 
- [ ] Add Filter Icon and Input to OverlayHeader
- [ ] Add Reset-Button
- [ ] Add Leave-Button 

### Complexity 
- small
